### ISSUE TITLE
gdal failed to build on 10.13

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#3163]
https://gist.github.com/cf8800463f9a3addce7daf0bf92243bd

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: error: no member named 'signbit'
 in the global namespace
using ::signbit;
      ~~^
```
