### ISSUE TITLE
check_bintray_mirror: Error: undefined method `first' for nil:NilClass

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/brew#3041]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew config` and `brew doctor` and included their output with your issue?

https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/6381/version=sierra/console

```
iMac-TMP:Homebrew joe$ brew pull https://github.com/Homebrew/homebrew-core/pull/16667
==> Fetching patch 
Patch: https://github.com/Homebrew/homebrew-core/pull/16667.patch
######################################################################## 100.0%
==> Applying patch
Applying: imagemagick@6 6.9.9-6
Error: undefined method `first' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/dev-cmd/pull.rb:610:in `check_bintray_mirror'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/pull.rb:165:in `block (3 levels) in pull'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/pull.rb:164:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/pull.rb:164:in `grep'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/pull.rb:164:in `block (2 levels) in pull'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/pull.rb:152:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/pull.rb:152:in `block in pull'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/pull.rb:71:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/pull.rb:71:in `pull'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

This happens if the tarball is not on Bintray yet for a formula we mirror to Bintray (e.g. imagemagick).

```
ae4bafdb365cfa380d129b0a03bd99a1e4d960a4 is the first bad commit
commit ae4bafdb365cfa380d129b0a03bd99a1e4d960a4
Author: Markus Reiter <me@reitermark.us>
Date:   Tue Aug 8 18:10:13 2017 +0200

    Simplify CurlDownloadStrategy.

:040000 040000 b15c81e7126ee2555fddf4bcb14d9168bf4faf5f 4bffd1cd11b4d551b5bf1f39f28e4d459553df2f M	Library
```

CC @reitermarkus @MikeMcQuaid
