### ISSUE TITLE
Error: undefined method `stage' for nil:NilClass

### ISSUE THREAD

**Issue by hutson** [Homebrew/brew#9521]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Force install the pre-compiled bottle of `htop`.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

$ brew update
Already up-to-date.

$ brew update
Already up-to-date.

$ brew install htop --force-bottle --debug --verbose
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/htop.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/shims/scm/git --version
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/m4.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/perl.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/expat.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libbsd.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/berkeley-db.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/automake.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libtool.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python@3.9.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ncurses.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gpatch.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zlib.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bzip2.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libffi.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/unzip.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zip.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/hutson/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/patchelf.rb
==> Downloading https://linuxbrew.bintray.com/bottles/htop-3.0.3_1.x86_64_linux.bottle.tar.gz
/usr/bin/curl --disable --globoff --show-error --user-agent Linuxbrew/2.6.1-41-ga6800dc\ \(Linux\;\ x86_64\ Ubuntu\ 20.04.1\ LTS\)\ curl/7.68.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://linuxbrew.bintray.com/bottles/htop-3.0.3_1.x86_64_linux.bottle.tar.gz
Already downloaded: /home/hutson/.cache/Homebrew/downloads/97ac4eccddb02fab7b2abccd1399d6666b2634e63c25a41abad8d9c5115255a6--htop-3.0.3_1.x86_64_linux.bottle.tar.gz
==> Verifying checksum for '97ac4eccddb02fab7b2abccd1399d6666b2634e63c25a41abad8d9c5115255a6--htop-3.0.3_1.x86_64_linux.bottle.tar.gz'.
Error: undefined method `stage' for nil:NilClass
Please report this issue:
https://docs.brew.sh/Troubleshooting
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:1130:in `block in pour'
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:318:in `block in cd'
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:318:in `chdir'
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:318:in `cd'
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:1129:in `pour'
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:393:in `install'
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:384:in `install_formula'
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:297:in `block in install'
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:295:in `each'
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:295:in `install'
/home/hutson/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'

  </pre>
</details>

## What you expected to happen

For `htop` to be successfully extracted into the appropriate Linuxbrew directories.

## Step-by-step reproduction instructions (by running `brew` commands)

```
brew install htop --force-bottle
```

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew config
HOMEBREW_VERSION: 2.6.1-41-ga6800dc
ORIGIN: https://github.com/Homebrew/brew
HEAD: a6800dc8534b044abcfc8aa1dc12bbae684122e9
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 2cf63af7103c225e550ca2ebbdf5e63102a98594
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/hutson/.linuxbrew
HOMEBREW_REPOSITORY: /home/hutson/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/hutson/.linuxbrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.3 => /home/hutson/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit skylake
Clang: N/A
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.0-56-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.1 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc: N/A
xorg: N/A

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
</pre>

As seen above, `brew doctor` points out that Homebrew is installed under my home directory and not `/home/linuxbrew`, an intentional decision, and the reason why I am attempting to force install the bottle for `htop`.

**Comment by MikeMcQuaid** [comment]
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Twitter or any other official channels. You are responsible for resolving
> any issues you experience while you are running this
> unsupported configuration.

Closing based on this. 

We'll review PRs to address this or one of the @Homebrew/linux people might be willing to open a PR for this.

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `util-linux`.

If it's an option for you, you could open a ticket with your information systems department to ask that they create a `linuxbrew` role account with home directory `/home/linuxbrew`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below. On macOS the default installation directory is `/usr/local`. On Linux the default installation directory is `/home/linuxbrew/.linuxbrew`.

See https://docs.brew.sh/FAQ#why-is-the-default-installation-prefix-homelinuxbrewlinuxbrew-on-linux

**Comment by sjackman** [comment]
`htop` is `cellar :any`, and so it should be possible to use this bottle, even when Homebrew is installed in the user's home directory.

**Comment by sjackman** [comment]
Steps to reproduce this issue on macOS:
```console
$ git clone --reference=/usr/local/Homebrew https://github.com/Homebrew/brew ~/.homebrew
$ git clone --reference=/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core https://github.com/Homebrew/homebrew-core ~/.homebrew/Library/Taps/homebrew/homebrew-core
$ ~/.homebrew/bin/brew install --force-hello hello
==> Downloading https://homebrew.bintray.com/bottles/hello-2.10.catalina.bottle.
Already downloaded: /Users/shaun.jackman/Library/Caches/Homebrew/downloads/6a8a266068965d3a7ea16bfe4821367cb94c47f904e7fc23ec61fad8a9859c54--hello-2.10.catalina.bottle.tar.gz
Error: undefined method `stage' for nil:NilClass
```

**Comment by sjackman** [comment]
This issue was introduced by PR https://github.com/Homebrew/brew/pull/9481.
`git -C $(brew --repo) revert --no-edit 0f9bad0052ed6ef225dbf5dce8c1e292d1c10fbc` will resolve it, after which `brew install htop` should work as expected.

**Comment by sjackman** [comment]
This issue is resolved by PR https://github.com/Homebrew/brew/pull/10024

**Comment by sjackman** [comment]
```
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': transfer closed with outstanding read data remaining
```
https://github.com/Homebrew/brew/pull/10024/checks?check_run_id=1555667540#step:2:20

**Comment by sjackman** [comment]
This issue has been resolved by PRs https://github.com/Homebrew/brew/pull/10024 and https://github.com/Homebrew/brew/pull/10025 and will be fixed by the next stable release of Homebrew 2.6.3.

**Comment by IgorOne** [comment]
I like the entitlement of the dude who introduced this stupid bug in the first place to close the issue before it was resolved.

**Comment by reitermarkus** [comment]
@IgorOne, you are also not entitled to receive a bug fix for an unsupported configuration from volunteers working on this project.

Please mind your attitude and read our code of conduct: https://github.com/Homebrew/.github/blob/HEAD/CODE_OF_CONDUCT.md#code-of-conduct
