### PR TITLE
dev-cmd/update-license-data: Fix "undefined variable `latest_tag`"

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

- This was broken by some refactoring in https://github.com/Homebrew/brew/pull/8215.
- I noticed that the [Actions runs for the scheduled task](https://github.com/Homebrew/brew/runs/966560393?check_suite_focus=true#step:4:17) had a funny way of succeeding:

```
==> Updating SPDX license data...
==> git add
Error: undefined local variable or method `latest_tag' for Homebrew:Module
Please report this issue:
==> git commit
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/update-license-data.rb:38:in `update_license_data'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:112:in `<main>'
```

### CODE REVIEW

**Comment by reitermarkus** [comment]
That instance variable is not shared between these two modules.

**Comment by issyl0** [comment]
Oh... OH, I should read the output I get. "Didn't error, fix must work" is different from "didn't error because there are no changes so it would never have got to the `commit` phase":

```
➜ brew update-license-data --commit
==> Updating SPDX license data...
######################################################################## 100.0%
==> git add
==> git commit
On branch fix-undefined-variable-latest_tag-spdx-license
Your branch is up to date with 'issyl0/fix-undefined-variable-latest_tag-spdx-license'.

nothing to commit, working tree clean
```

It's too hot. 😆 I'll let @SeekingMeaning fix it as he's actually touched this code before. 😳
