### PR TITLE
Fix "undefined local variable" error in update-report

### PR DESCRIPTION
**Pull request by dduugg**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----
Resolves an error introduced in https://github.com/Homebrew/brew/commit/2451d017f9ebbf6b3f5fd79f15e048d2c109145a#diff-05ec45190dab3db11df80b2c154648c8023837fa34917dce9d1bcde0acf9c005L282
If you have a few minutes and you're willing to untap `core`, you should be able to repro with:

```
$ brew untap homebrew/core; HOMEBREW_NO_INSTALL_FROM_API=1 brew update-report
Untapping homebrew/core...
Untapped 3 commands and 6552 formulae (15,331 files, 710.4MB).
==> Tapping homebrew/core
Cloning into '/opt/homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 1429703, done.
remote: Counting objects: 100% (318/318), done.
remote: Compressing objects: 100% (157/157), done.
remote: Total 1429703 (delta 190), reused 268 (delta 161), pack-reused 1429385
Receiving objects: 100% (1429703/1429703), 549.69 MiB | 3.90 MiB/s, done.
Resolving deltas: 100% (997762/997762), done.
Tapped 3 commands and 6554 formulae (6,906 files, 604.5MB).
Error: undefined local variable or method `core_tap' for Homebrew:Module
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/cmd/update-report.rb:318:in `install_core_tap_if_necessary'
/opt/homebrew/Library/Homebrew/cmd/update-report.rb:115:in `output_update_report'
/opt/homebrew/Library/Homebrew/cmd/update-report.rb:42:in `update_report'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

I've also enabled typechecking in `update-report`, which would have caught this error

### CODE REVIEW

File: Library/Homebrew/cmd/update-report.rb [hunk 1]
```diff
@@ -671,7 +671,7 @@ def dump(updated_formula_report: true)
     return if outdated_formulae.blank? && outdated_casks.blank?
 
     outdated_formulae = outdated_formulae.count
-    outdated_casks = outdated_casks.count
+    outdated_casks = T.must(outdated_casks).count
```
Comment (reitermarkus) [inline Library/Homebrew/cmd/update-report.rb:674]: Can we initialize these with `[]` instead to avoid this?

Comment (dduugg) [reply Library/Homebrew/cmd/update-report.rb:674]: Yep! One sec.

**Review by MikeMcQuaid — APPROVED** [review]
Good catch, thanks @dduugg!

**Comment by hasufell** [comment]
I'm still seeing this in CI: https://gitlab.haskell.org/haskell/cabal/-/jobs/1398914

```
+ brew update
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:cf9137b1da5568d4949f71161a69b101f60ddb765e94d2b423c9801b67a1cb43
######################################################################## 100.0%
==> Pouring portable-ruby-2.6.8_1.arm64_big_sur.bottle.tar.gz
==> Homebrew has enabled anonymous aggregate formula and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics have been recorded yet (nor will be during this `brew` run).
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
==> Tapping homebrew/core
Cloning into '/private/var/lib/gitlab-runner/builds/7KQsmDei/0/haskell/cabal/.brew/Library/Taps/homebrew/homebrew-core'...
Tapped 3 commands and 6[55](https://gitlab.haskell.org/haskell/cabal/-/jobs/1398914#L55)9 formulae (6,911 files, 605.5MB).
Error: undefined local variable or method `core_tap' for Homebrew:Module
```

**Comment by dduugg** [comment]
> I'm still seeing this in CI: https://gitlab.haskell.org/haskell/cabal/-/jobs/1398914
> 
> ```
> + brew update
> ==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:cf9137b1da5568d4949f71161a69b101f60ddb765e94d2b423c9801b67a1cb43
> ######################################################################## 100.0%
> ==> Pouring portable-ruby-2.6.8_1.arm64_big_sur.bottle.tar.gz
> �==> Homebrew has enabled anonymous aggregate formula and cask analytics.
> Read the analytics documentation (and how to opt-out) here:
>   https://docs.brew.sh/Analytics
> No analytics have been recorded yet (nor will be during this `brew` run).
> ==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
>   https://github.com/Homebrew/brew#donations
> ==> Tapping homebrew/core
> Cloning into '/private/var/lib/gitlab-runner/builds/7KQsmDei/0/haskell/cabal/.brew/Library/Taps/homebrew/homebrew-core'...
> Tapped 3 commands and 6[55](https://gitlab.haskell.org/haskell/cabal/-/jobs/1398914#L55)9 formulae (6,911 files, 605.5MB).
> Error: undefined local variable or method `core_tap' for Homebrew:Module
> ```

Hmm, not sure why that would be the case, perhaps there's some sort of caching happening? It looks like you might be using the latest master in CI, which I suspect is in inherently more fragile than checking out an official release: https://gitlab.haskell.org/haskell/cabal/-/blob/master/.gitlab/brew.sh#L6

You could pin that to a specific release for improved stability. You could also try to check out the latest release, something like this might do the trick: 
```
git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
```

**Comment by dduugg** [comment]
@gMan1990 I'm sorry you're having this issue. What does `brew --version` output?

**Comment by gMan1990** [comment]
@dduugg 

```text
Homebrew 4.0.5
Homebrew/homebrew-core (git revision 0f4afdec394; last commit 2023-03-10)

Darwin edydeMacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
```

**Comment by dduugg** [comment]
Oh, this fix didn't make it into the latest release 🤦 
Let me see if someone can cut a new release for you.

**Comment by dduugg** [comment]
Homebrew version 4.0.6 was just [released](https://github.com/Homebrew/brew/releases/tag/4.0.6), which incorporates this patch.
