### ISSUE TITLE
Latest gcc update breaks building Emacs with native-compilation

### ISSUE THREAD

**Issue by dr-scsi** [Homebrew/brew#18646]
### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.4.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 35ebf4a047b00b2b3de33ba0081d71293cdadede
Last commit: 6 days ago
Core tap JSON: 27 Oct 08:38 UTC
Core cask tap JSON: 27 Oct 08:38 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 16.0.0 build 1600
Git: 2.47.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0.1-arm64
CLT: 16.0.0.0.1.1724870825
Xcode: N/A
Rosetta 2: false
```

### What were you trying to do (and why)?

I build Emacs myself with a small script and it seems that updating gcc to 14.2.0_1 breaks the option native-compilation which relies on libgccjit.  It used to work without any problems with 14.2.0 build.

Some info:

```
$ brew info gcc
==> gcc: stable 14.2.0 (bottled), HEAD
GNU compiler collection
https://gcc.gnu.org/
Installed
/opt/homebrew/Cellar/gcc/14.2.0_1 (1,914 files, 459.9MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-10-24 at 21:36:05
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/g/gcc.rb
License: GPL-3.0-or-later WITH GCC-exception-3.1
==> Dependencies
Build: make ✔
Required: gmp ✔, isl ✔, libmpc ✔, mpfr ✔, zstd ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 130,442 (30 days), 426,448 (90 days), 1,541,340 (365 days)
install-on-request: 67,149 (30 days), 203,183 (90 days), 648,004 (365 days)
build-error: 1,008 (30 days)
```

```
$ brew info libgccjit
==> libgccjit: stable 14.2.0 (bottled), HEAD
JIT library for the GNU compiler collection
https://gcc.gnu.org/
Installed
/opt/homebrew/Cellar/libgccjit/14.2.0 (15 files, 41.0MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-08-26 at 08:59:54
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/lib/libgccjit.rb
License: GPL-3.0-or-later WITH GCC-exception-3.1
==> Dependencies
Required: gmp ✔, isl ✔, libmpc ✔, mpfr ✔, zstd ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 817 (30 days), 3,358 (90 days), 10,267 (365 days)
install-on-request: 556 (30 days), 2,291 (90 days), 7,072 (365 days)
build-error: 9 (30 days)
```

```
$ gcc --version
Apple clang version 16.0.0 (clang-1600.0.26.3)
Target: arm64-apple-darwin24.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### What happened (include all command output)?

I use a small script to build Emacs which looks like this:

```
git clean -fdx --exclude=ChangeLog

./autogen.sh

GCC_INC=$(realpath $(brew --prefix gcc))
GCC_INC_DIR=${GCC_INC}/include
GCC_LIB_DIR=${GCC_INC}/lib/gcc/current

GCCJIT_INC=$(realpath $(brew --prefix libgccjit))
GCCJIT_INC_DIR=${GCCJIT_INC}/include
GCCJIT_LIB_DIR=${GCCJIT_INC}/lib/gcc/current

GMP_INC=$(realpath $(brew --prefix gmp))
GMP_INC_DIR=${GMP_INC}/include
GMP_LIB_DIR=${GMP_INC}/lib

XML_INC=$(realpath $(brew --prefix libxml2))
XML_INC_DIR=${XML_INC}/include
XML_LIB_DIR=${XML_INC}/lib

CPPFLAGS="-I${GCC_INC_DIR} -I${GCCJIT_INC_DIR} -I${GMP_INC_DIR} -I${XML_INC_DIR} " \
LDFLAGS="-L${GCC_LIB_DIR} -L${GMP_LIB_DIR} -L${XML_LIB_DIR} " \
CFLAGS="-O2 -g0 -pipe" \
./configure \
    --with-ns \
    --without-pop \
    --without-mailutils \
    --with-threads \
    --with-modules \
    --with-native-compilation \
    --without-compress-install

# make -j8
```

After updating to 14.2.0_1, running `configure` for Emacs as above says:

```
checking for gcc_jit_context_acquire in -lgccjit... yes
checking for libgccjit.h... yes
configure: error: The installed libgccjit failed to compile and run a test program using
the libgccjit library; see config.log for the details of the failure.
The test program can be found here:
<https://gcc.gnu.org/onlinedocs/jit/intro/tutorial01.html>.
You can try compiling it yourself to investigate the issues.
Please report the issue to your distribution if libgccjit was installed
through that.
You can find the instructions on how to compile and install libgccjit from
source on this site:
<https://gcc.gnu.org/wiki/JIT>.
```

This is the part from `config.log` (line-breaks added for better legibility):

```
configure:28207: checking for libgccjit.h
configure:28207: gcc -c -g3 -O2 
-isystem /opt/homebrew/Cellar/librsvg/2.58.4/include/librsvg-2.0 
-isystem /opt/homebrew/Cellar/gdk-pixbuf/2.42.12/include/gdk-pixbuf-2.0 
-isystem /opt/homebrew/Cellar/libtiff/4.7.0/include 
-isystem /opt/homebrew/opt/zstd/include 
-isystem /opt/homebrew/Cellar/xz/5.6.3/include 
-isystem /opt/homebrew/Cellar/jpeg-turbo/3.0.4/include 
-isystem /opt/homebrew/Cellar/glib/2.82.2/include 
-isystem /opt/homebrew/Cellar/glib/2.82.2/include/glib-2.0 
-isystem /opt/homebrew/Cellar/glib/2.82.2/lib/glib-2.0/include 
-isystem /opt/homebrew/opt/gettext/include 
-isystem /opt/homebrew/Cellar/pcre2/10.44/include 
-isystem /opt/homebrew/Cellar/cairo/1.18.2/include/cairo 
-isystem /opt/homebrew/Cellar/fontconfig/2.15.0/include 
-isystem /opt/homebrew/opt/freetype/include/freetype2 
-isystem /opt/homebrew/opt/libpng/include/libpng16 
-isystem /opt/homebrew/Cellar/libxext/1.3.6/include 
-isystem /opt/homebrew/Cellar/libxrender/0.9.11/include 
-isystem /opt/homebrew/Cellar/libx11/1.8.10/include 
-isystem /opt/homebrew/Cellar/libxcb/1.17.0/include 
-isystem /opt/homebrew/Cellar/libxau/1.0.11/include 
-isystem /opt/homebrew/Cellar/libxdmcp/1.1.5/include 
-isystem /opt/homebrew/Cellar/pixman/0.42.2/include/pixman-1 
-isystem /opt/homebrew/Cellar/xorgproto/2024.1/include 
-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/ffi    conftest.c >&5
conftest.c:155:10: fatal error: 'libgccjit.h' file not found
  155 | #include <libgccjit.h>
      |          ^~~~~~~~~~~~~
1 error generated.
configure:28207: $? = 1
```

### What did you expect to happen?

Emacs used to build fine with the way I built it before 14.2.0_1. I expect it to build with native-compilation again.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Update brew installation and run the bash script above in a local Emacs git repo.
```

**Comment by MikeMcQuaid** [comment]
> * This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at [Homebrew/homebrew-core/issues/new/choose](https://github.com/Homebrew/homebrew-core/issues/new/choose) instead.

It does so: moving to homebrew/core
