### PR TITLE
Remove unneeded `curl_openssl_or_deps` invocation

### LINKED ISSUE #5629: brew audit throws error: "Error: undefined local variable or method `curl_openssl_or_deps`"
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

I updated a taped formula ([miktex/miktex](https://github.com/MiKTeX/homebrew-miktex)) and  wanted to audit it like a new formula with `brew audit --fix --new-formula miktex`.

# What happened (include command output)

I got this exception message.

<details>
  <summary>Command output</summary>
  <pre>
brew audit --fix --new-formula miktex
Error: undefined local variable or method `curl_openssl_or_deps' for #<Homebrew::ResourceAuditor:0x00007fbe4bd970b8>
Did you mean?  curl_download
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1137:in `block in audit_urls'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1128:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1128:in `audit_urls'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1050:in `audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:652:in `block in audit_specs'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:648:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:648:in `audit_specs'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1005:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:998:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:998:in `audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:157:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:152:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:152:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
  </pre>
</details>

# What you expected to happen

I expected the normal audit report.

# Step-by-step reproduction instructions (by running `brew` commands)

This error is caused by #5626.

# Other information

<details>
  <summary><code>brew config</code> output</summary>
  <pre>
HOMEBREW_VERSION: 1.9.3-41-g76b3c3d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 76b3c3dbe2ea1dcfb76b0036ef06804be7c590a4
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 63063c790f814ff24a6d66631b7174f59e2dbeaa
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LOGS: /Users/spt/Library/Logs/Homebrew
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.2, 10.0.2, 1.8.0_202, 1.6.0_65-b14-468
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
  </pre>
</details>
<details>
  <summary><code>brew doctor</code> output</summary>
  <pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: You have installed Bitdefender. The "Traffic Scan" option interferes with
Homebrew's ability to download packages. See:
  https://github.com/Homebrew/brew/issues/5558

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.
  </pre>
</details>

### PR DESCRIPTION
**Pull request by claui**
@Homebrew/maintainers Please review, as this issue is blocking CI. Thanks!

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb). **Removed code has never been covered by tests.**
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This fixes a regression introduced in #5626, which removed `curl_openssl_or_deps` and left a single call in the code.

Fixes #5629.

### CODE REVIEW

**Comment by igas** [comment]
LGTM

**Comment by MikeMcQuaid** [comment]
Thanks @claui!
