### ISSUE TITLE
`brew unbottled` errors out for some formulae

### ISSUE THREAD

**Issue by carlocab** [Homebrew/brew#11456]
### `brew config` output

```shell
❯ brew config
HOMEBREW_VERSION: 3.1.9-70-g6de6218
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6de6218f06459c70ad84b54e9324a7f3de884917
Last commit: 53 seconds ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6941435938fae4e5ca8c3d08be039443d50fa1ca
Core tap last commit: 7 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT: set
HOMEBREW_BOOTSNAP: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_COLOR: set
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: nvim
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_FORCE_BREWED_GIT: set
HOMEBREW_GITHUB_PACKAGES_TOKEN: set
HOMEBREW_GITHUB_PACKAGES_USER: carlocab
HOMEBREW_GIT_EMAIL: 30379873+carlocab@users.noreply.github.com
HOMEBREW_GIT_NAME: Carlo Cabrera
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_PRY: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit icelake
Clang: 12.0.5 build 1205
Git: 2.31.1 => /usr/local/opt/git/bin/git
Curl: 7.77.0 => /usr/local/opt/curl/bin/curl
macOS: 11.4-x86_64
CLT: 12.5.0.22.9
Xcode: N/A
```

### `brew doctor` output

```shell
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run `brew unbottled` to check for formulae without ARM bottles.

### What happened (include all command output)?

```
❯ brew unbottled --tag=arm64_big_sur pillar
==> Populating dependency tree...
==> :arm64_big_sur bottle status
Error: undefined method `arch' for #<OS::Mac::Version:0x00007fc94389ba70>
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/dev-cmd/unbottled.rb:197:in `block (2 levels) in output_unbottled'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:83:in `all?'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:83:in `method_missing'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/unbottled.rb:182:in `block in output_unbottled'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/unbottled.rb:159:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/unbottled.rb:159:in `output_unbottled'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/unbottled.rb:74:in `unbottled'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

The same happens with `signal-cli` and `wartremover`. More generally, I think it happens when a formula has a `depends_on arch: :x86_64` somewhere in its dependency tree.

### What did you expect to happen?

No errors.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew unbottled --tag=arm64_big_sur pillar
```

**Comment by carlocab** [comment]
With `git bisect`:
```
20d86c01850df6855e5e8b5958d3e6892de87190 is the first bad commit
commit 20d86c01850df6855e5e8b5958d3e6892de87190
Author: Bo Anderson <mail@boanderson.me>
Date:   Thu Apr 8 13:45:15 2021 +0100

    Refactor some tag handling into a Utils::Bottles::Tag class

 Library/Homebrew/dev-cmd/bottle.rb                 |  22 ++---
 Library/Homebrew/dev-cmd/dispatch-build-bottle.rb  |  31 +++---
 Library/Homebrew/dev-cmd/unbottled.rb              |  10 +-
 Library/Homebrew/extend/os/mac/utils/bottles.rb    |  14 +--
 Library/Homebrew/os/mac/version.rb                 |  38 ++-----
 Library/Homebrew/software_spec.rb                  |  38 ++++---
 Library/Homebrew/test/formula_spec.rb              |   2 +-
 Library/Homebrew/test/os/mac/version_spec.rb       |  20 ----
 Library/Homebrew/test/software_spec/bottle_spec.rb |  16 +--
 .../test/support/fixtures/testball_bottle.rb       |   2 +-
 .../support/fixtures/testball_bottle_cellar.rb     |   2 +-
 .../Homebrew/test/utils/bottles/collector_spec.rb  |  12 +--
 Library/Homebrew/test/utils/bottles/tag_spec.rb    |  39 ++++++++
 Library/Homebrew/utils/bottles.rb                  | 109 ++++++++++++++++++++-
 14 files changed, 227 insertions(+), 128 deletions(-)
 create mode 100644 Library/Homebrew/test/utils/bottles/tag_spec.rb
```
I started with da811373d3f876da72d53c2828fd4cacefdba210 as the first good commit.
