### ISSUE TITLE
Gedit failed to build in 10.11.6

### ISSUE THREAD

**Issue by mariomac** [Homebrew/brew#1222]
# General troubleshooting steps:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Gedit crashes on start with the quoted output. This was reported on https://github.com/Homebrew/brew/issues/1219 but the proposed solution didn't work. I have reported it again by following the requested steps on the Troubleshooting page.

Please find linked the output of `brew gist-logs` as well as the output of invoking `gedit` from the command line.

[https://gist.github.com/adcb0472ed398d7cd279a4c8d84e2936]

> 2016-10-04 09:38:01.591 gedit[11562:514377] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
> 
> (gedit:11562): Gdk-WARNING **: GdkQuartzDisplay does not implement the monitor vfuncs
> 
> (gedit:11562): Gtk-WARNING **: Could not load a pixbuf from icon theme.
> This may indicate that pixbuf loaders or the mime database could not be found.
> 
> ** (gedit:11562): WARNING **: Could not load theme icon user-bookmarks-symbolic: No se ha reconocido el formato de imagen del archivo
> 
> ** (gedit:11562): WARNING **: Could not load theme icon user-home-symbolic: No se ha reconocido el formato de imagen del archivo
> 
> ** (gedit:11562): WARNING **: Could not load theme icon drive-harddisk-symbolic: No se ha reconocido el formato de imagen del archivo
> **
> Gtk:ERROR:gtkiconhelper.c:493:ensure_surface_for_gicon: assertion failed: (destination)
> Abort trap: 6

**Comment by mariomac** [comment]
Closed according to the instructions in #1219
